# Generated by Django 3.1.12 on 2021-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_log_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='app_eui',
            field=models.CharField(blank=True, help_text='App EUI', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='dev_eui',
            field=models.CharField(blank=True, help_text='Device EUI', max_length=256, null=True),
        ),
    ]
